/* ============================================================
   PACKAGES DATA — Sri Balaji Travels
   Single source of truth. Used by index.html, tirupathi.html,
   and package.html
   ============================================================ */

const PACKAGES = [

  /* ── TIRUMALA / DARSHAN ─────────────────────────────── */
  {
    id: "tirumala-basic",
    name: "Tirumala Darshan Ride",
    category: "tirumala",
    tag: "Quick Darshan",
    tagClass: "",
    popular: false,
    price: 2799,
    duration: "Half Day",
    routeShort: "Tirupati → Tirumala → Tirupati",
    routeFull: ["Tirupati", "Tirumala", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["Pickup & Drop", "Tirumala Darshan", "5 / 7 Seater"],
    description: "A simple, focused darshan ride to Tirumala and back. Perfect for devotees who want a quick and efficient visit to Lord Venkateswara.",
    note: "Basic darshan ride. Upgrade to Darshan + Sightseeing for more value.",
    driverCost4s: "2000–2300",
    commission4s: "300–800",
    price7s: null,
    includes: ["Cab pickup from your location", "Tirumala darshan drop & pickup", "Return drop"],
    excludes: ["Entry tickets", "GST", "Accommodation"]
  },
  {
    id: "tirumala-sightseeing",
    name: "Tirumala Darshan + Sightseeing",
    category: "tirumala",
    tag: "Most Popular ⭐",
    tagClass: "tag-popular",
    popular: true,
    price: 4299,
    duration: "Full Day",
    routeShort: "Tirupati → Tirumala → Sightseeing → Tirupati",
    routeFull: ["Tirupati", "Tirumala", "Japali Falls", "Tirupati"],
    image: "images/p2.jpg",
    highlights: ["Tirumala Darshan", "Local Sightseeing", "Japali Falls +₹500"],
    description: "Our most booked package — combines the divine Tirumala darshan with peaceful local sightseeing including Japali Theertham. The perfect full-day spiritual experience.",
    note: "Main package ⭐. Japali Theertham visit available at +₹500 extra.",
    driverCost4s: 3000,
    commission4s: 1299,
    price7s: null,
    includes: ["Cab pickup & drop", "Tirumala darshan", "Local sightseeing stops", "Experienced driver-guide"],
    excludes: ["Japali Falls (₹500 extra)", "Entry tickets", "GST"]
  },
  {
    id: "tirupati-temples-basic",
    name: "Tirupati Temple Tour",
    category: "tirupati",
    tag: "Entry Level",
    tagClass: "",
    popular: false,
    price: 2299,
    duration: "Half Day",
    routeShort: "4 Temples · Tirupati",
    routeFull: ["Kapila Theertham", "ISKCON", "Padmavathi Temple", "Govinda Raja"],
    image: "images/p3.jpg",
    highlights: ["4 Temple Visits", "Kapila Theertham", "Padmavathi Temple", "ISKCON & Govinda Raja"],
    description: "Visit four of Tirupati's most revered temples in a single comfortable trip. Great for first-time visitors who want to experience the spiritual richness of the town.",
    note: "Entry-level sightseeing package for Tirupati town temples.",
    driverCost4s: 1500,
    commission4s: "700–800",
    price7s: null,
    includes: ["Cab pickup & drop", "4 temple visits", "Driver guide"],
    excludes: ["Entry tickets", "GST", "Prasadam"]
  },
  {
    id: "tirupati-complete",
    name: "Complete Tirupati Darshan",
    category: "tirupati",
    tag: "Full Darshan",
    tagClass: "",
    popular: true,
    price: 3499,
    duration: "Full Day",
    routeShort: "All Tirupati Temples",
    routeFull: ["Tirupati", "All Major Temples", "Sightseeing", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["All Major Temples", "Full Day Tour", "Gudimalla +₹500"],
    description: "A comprehensive spiritual tour covering all major temples and sacred sites in and around Tirupati. Thorough, unhurried, and deeply fulfilling.",
    note: "Gudimalla temple visit available as ₹500 add-on.",
    driverCost4s: 2500,
    commission4s: "900–1000",
    price7s: null,
    includes: ["Full day cab", "All major temples", "Driver guide", "Flexible schedule"],
    excludes: ["Gudimalla (₹500 extra)", "Entry tickets", "GST"]
  },

  /* ── OUTSTATION DARSHAN ─────────────────────────────── */
  {
    id: "kalahasti",
    name: "Kalahasti Darshan",
    category: "outstation",
    tag: "Rahu-Ketu Pooja",
    tagClass: "",
    popular: false,
    price: 3299,
    duration: "Full Day",
    routeShort: "Tirupati → Kalahasti → Tirupati",
    routeFull: ["Tirupati", "Srikalahasti", "Tirupati"],
    image: "images/p2.jpg",
    highlights: ["Kalahasti Temple", "Rahu-Ketu Pooja", "Add Tirupati Sightseeing +₹1500"],
    description: "Visit the famous Sri Kalahasteeswara temple, known for Rahu-Ketu pooja. One of the Pancha Bhuta Stalas dedicated to Lord Shiva.",
    note: "Add Tirupati town sightseeing for ₹1500–₹2000 extra.",
    driverCost4s: 2300,
    commission4s: "900–1000",
    price7s: null,
    includes: ["Cab pickup & drop", "Kalahasti temple visit", "Driver guide"],
    excludes: ["Pooja charges", "Entry tickets", "GST"]
  },

  /* ── ONE-DAY ROUTES ─────────────────────────────────── */
  {
    id: "route-vakulamatha",
    name: "Vakulamatha – Mangapuram – Kanipakam",
    category: "one-day",
    tag: "Short Premium",
    tagClass: "",
    popular: false,
    price: 3899,
    duration: "Full Day",
    routeShort: "Tirupati → 3 Stops → Tirupati",
    routeFull: ["Tirupati", "Vakulamatha", "Mangapuram", "Kanipakam", "Tirupati"],
    image: "images/p3.jpg",
    highlights: ["Vakulamatha Temple", "Mangapuram Shrine", "Kanipakam Ganesha"],
    description: "A compact yet deeply spiritual route covering three important shrines in a single day. The Kanipakam Vinayaka temple is especially revered for wish fulfillment.",
    note: "Short premium route. Comfortable for families.",
    driverCost4s: 3000,
    commission4s: 900,
    price7s: null,
    includes: ["Full day cab", "3 temple visits", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-mangapuram-golden",
    name: "Mangapuram + Golden Temple",
    category: "one-day",
    tag: "Medium Route",
    tagClass: "",
    popular: false,
    price: 5099,
    duration: "Full Day",
    routeShort: "Tirupati → Mangapuram → Golden Temple → Tirupati",
    routeFull: ["Tirupati", "Mangapuram", "Golden Temple", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["Mangapuram Shrine", "Golden Temple (Sripuram)", "Scenic Drive"],
    description: "Visit the magnificent Sripuram Golden Temple — one of the largest in India — along with the serene Mangapuram shrine. A visually stunning and spiritually rich experience.",
    note: "Medium route. Golden Temple visit is a highlight.",
    driverCost4s: 4000,
    commission4s: 1100,
    price7s: null,
    includes: ["Full day cab", "2 major sites", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-kanipakam-golden-arunachalam",
    name: "Kanipakam – Golden Temple – Arunachalam",
    category: "one-day",
    tag: "Long Route",
    tagClass: "tag-premium",
    popular: true,
    price: 8199,
    duration: "Full Day",
    routeShort: "Tirupati → Kanipakam → Golden Temple → Arunachalam → Tirupati",
    routeFull: ["Tirupati", "Kanipakam", "Sripuram Golden Temple", "Tiruvannamalai", "Tirupati"],
    image: "images/p2.jpg",
    highlights: ["Kanipakam Ganesha", "Golden Temple Sripuram", "Arunachaleswara Temple", "Full Day Premium"],
    description: "Our longest and most immersive one-day spiritual circuit. Three legendary shrines across two states — a journey that covers Ganesha, Goddess Lakshmi, and Lord Shiva in a single blessed day.",
    note: "Long premium route. Early start recommended.",
    driverCost4s: 6500,
    commission4s: 1700,
    price7s: null,
    includes: ["Full day premium cab", "3 temple visits", "Experienced driver-guide"],
    excludes: ["Entry tickets", "GST", "Meals"]
  },
  {
    id: "route-kanchi-temples",
    name: "Kanchi Temples Tour",
    category: "one-day",
    tag: "Popular Temple Route",
    tagClass: "",
    popular: true,
    price: 5699,
    duration: "Full Day",
    routeShort: "Tirupati → Tiruthani → Kanchi (3 Temples) → Tirupati",
    routeFull: ["Tirupati", "Tiruthani", "Kanchipuram Temples (3)", "Tirupati"],
    image: "images/p3.jpg",
    highlights: ["Tiruthani Murugan", "Ekambareswarar", "Kamakshi Amman", "Varadharaja Perumal"],
    description: "Explore the ancient temple city of Kanchipuram — one of the seven sacred cities of India. Three iconic temples across the city, plus the Tiruthani Murugan shrine on the way.",
    note: "Popular temple route among pilgrims.",
    driverCost4s: 4500,
    commission4s: 1200,
    price7s: null,
    includes: ["Full day cab", "4 temple visits", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-tiruthani-appalayagunta",
    name: "Tiruthani – Appalayagunta – Padmavathi",
    category: "one-day",
    tag: "Medium Route",
    tagClass: "",
    popular: false,
    price: 4499,
    duration: "Full Day",
    routeShort: "Tirupati → Tiruthani → Appalayagunta → Padmavathi → Tirupati",
    routeFull: ["Tirupati", "Tiruthani", "Appalayagunta", "Padmavathi Temple", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["Tiruthani Murugan Temple", "Appalayagunta Shrine", "Padmavathi Temple"],
    description: "A balanced medium route combining three distinct spiritual stops. The Tiruthani Murugan temple, the peaceful Appalayagunta, and the beloved Padmavathi temple near Tirupati.",
    note: "Medium route. Well-balanced for a comfortable day.",
    driverCost4s: 3500,
    commission4s: 1000,
    price7s: null,
    includes: ["Full day cab", "3 temple visits", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-temple-circle",
    name: "Local Temple Circuit",
    category: "one-day",
    tag: "Long Local Circuit",
    tagClass: "",
    popular: false,
    price: 5799,
    duration: "Full Day",
    routeShort: "6-Stop Local Circuit",
    routeFull: ["Tirupati", "Narayana Vanam", "Nagalapuram", "Surutupalli", "Karveti", "Bugga Ramalingeswara", "Tirupati"],
    image: "images/p2.jpg",
    highlights: ["Narayana Vanam", "Nagalapuram", "Surutupalli", "Bugga Ramalingeswara"],
    description: "An extensive local temple circuit covering six sacred sites in and around Tirupati. Ideal for devotees who want to explore the lesser-known but equally divine shrines of this region.",
    note: "Long local circuit. Early start strongly recommended.",
    driverCost4s: 4500,
    commission4s: 1300,
    price7s: null,
    includes: ["Full day cab", "6 stops", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-ontimitta",
    name: "Ontimitta Darshan",
    category: "one-day",
    tag: "Standalone Route",
    tagClass: "",
    popular: false,
    price: 5099,
    duration: "Full Day",
    routeShort: "Tirupati → Ontimitta → Tirupati",
    routeFull: ["Tirupati", "Ontimitta", "Tirupati"],
    image: "images/p3.jpg",
    highlights: ["Ontimitta Kodandarama Temple", "Ancient Architecture", "Peaceful Village Temple"],
    description: "Visit the serene Kodandarama temple at Ontimitta — a beautifully preserved ancient temple with stunning architecture and a tranquil atmosphere away from the crowds.",
    note: "Standalone route. Great for devotees of Lord Rama.",
    driverCost4s: 4000,
    commission4s: 1100,
    price7s: null,
    includes: ["Full day cab", "Ontimitta temple visit", "Driver guide"],
    excludes: ["Entry tickets", "GST"]
  },
  {
    id: "route-tiruthani-kanchi-arunachalam",
    name: "Tiruthani – Kanchi – Arunachalam",
    category: "one-day",
    tag: "Long Premium ✨",
    tagClass: "tag-premium",
    popular: false,
    price: 8999,
    duration: "Full Day",
    routeShort: "Tirupati → Tiruthani → Kanchi → Arunachalam → Tirupati",
    routeFull: ["Tirupati", "Tiruthani", "Kanchipuram", "Tiruvannamalai", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["Tiruthani Murugan", "Kanchipuram Temples", "Arunachaleswara Temple", "Longest Route"],
    description: "The grandest one-day temple journey we offer. Three cities, multiple temples, and an extraordinary spiritual arc — from Murugan at Tiruthani to Lord Shiva at Arunachalam, through the temple city of Kanchipuram.",
    note: "Long premium route. Very early start required.",
    driverCost4s: 7000,
    commission4s: 2000,
    price7s: null,
    includes: ["Full day premium cab", "Multiple temples", "Experienced driver-guide"],
    excludes: ["Entry tickets", "GST", "Meals"]
  },

  /* ── MULTI-DAY ──────────────────────────────────────── */
  {
    id: "yatra-2day",
    name: "2-Day Premium Yatra",
    category: "multi-day",
    tag: "Best Value 🏆",
    tagClass: "tag-premium",
    popular: true,
    price: 11499,
    duration: "2 Days",
    routeShort: "7-Stop Grand Circuit",
    routeFull: ["Tirupati", "Kanipakam", "Golden Temple", "Arunachalam", "Kanchipuram", "Tiruthani", "Kalahasti", "Tirupati"],
    image: "images/p2.jpg",
    highlights: ["7 Sacred Sites", "2 Full Days", "Kanipakam to Kalahasti", "Stay Not Included"],
    description: "The ultimate spiritual journey — 7 of the most revered temples across Andhra Pradesh and Tamil Nadu spread over two full days. This is the trip devotees remember for life.",
    note: "Stay not included. We can assist with hotel bookings separately.",
    driverCost4s: 9000,
    commission4s: 2499,
    price7s: null,
    includes: ["2-day cab", "7 temple visits", "Experienced driver-guide", "Flexible itinerary"],
    excludes: ["Accommodation", "Entry tickets", "GST", "Meals"]
  },

  /* ── LOCAL & TRANSFERS ──────────────────────────────── */
  {
    id: "local-pickup",
    name: "Local Pickup & Drop",
    category: "transfer",
    tag: "Airport / Railway",
    tagClass: "",
    popular: false,
    price: 1349,
    duration: "As needed",
    routeShort: "Tirupati → Nearby → Tirupati",
    routeFull: ["Airport / Railway", "Hotel / Temple", "Airport / Railway"],
    image: "images/p3.jpg",
    highlights: ["Airport Pickup", "Railway Station Drop", "On-Time Guaranteed", "24/7 Available"],
    description: "Reliable airport and railway station transfers within Tirupati. On-time pickup, comfortable vehicles, and zero hassle for your arrival or departure.",
    note: "Includes airport and railway transfers. Don't mention these separately.",
    driverCost4s: 1000,
    commission4s: 350,
    price7s: null,
    includes: ["Pickup from airport/railway", "Drop at hotel or temple", "On-time service"],
    excludes: ["Waiting charges after 30 min", "GST"]
  },

  /* ── OUTSTATION ROUTES ──────────────────────────────── */
  {
    id: "tirupati-chennai",
    name: "Tirupati → Chennai",
    category: "outstation",
    tag: "One Way",
    tagClass: "",
    popular: false,
    price: 6999,
    duration: "One Way",
    routeShort: "Tirupati → Chennai",
    routeFull: ["Tirupati", "Chennai"],
    image: "images/p1.jpg",
    highlights: ["One-Way Drop", "City Centre Drop", "Airport Drop Available"],
    description: "Comfortable one-way cab service from Tirupati to Chennai. Whether you're heading to the city, airport, or railway station — we get you there smoothly.",
    note: "One-way trip. Return bookings available separately.",
    driverCost4s: 5500,
    commission4s: 1500,
    price7s: null,
    includes: ["One-way cab", "Toll charges", "Driver allowance"],
    excludes: ["Return trip", "GST"]
  },
  {
    id: "tirupati-bangalore",
    name: "Tirupati → Bangalore",
    category: "outstation",
    tag: "One Way",
    tagClass: "",
    popular: false,
    price: 6999,
    duration: "One Way",
    routeShort: "Tirupati → Bangalore",
    routeFull: ["Tirupati", "Bangalore"],
    image: "images/p2.jpg",
    highlights: ["One-Way Drop", "City Centre / Airport", "Comfortable Ride"],
    description: "Smooth one-way cab service from Tirupati to Bangalore. Perfect after your pilgrimage — sit back, relax, and we'll take care of the drive.",
    note: "One-way trip. Return bookings available separately.",
    driverCost4s: 5500,
    commission4s: 1500,
    price7s: null,
    includes: ["One-way cab", "Toll charges", "Driver allowance"],
    excludes: ["Return trip", "GST"]
  },
  {
    id: "tirupati-srisailam",
    name: "Tirupati → Srisailam",
    category: "outstation",
    tag: "Long Distance",
    tagClass: "tag-premium",
    popular: false,
    price: 17500,
    duration: "Full Day",
    routeShort: "Tirupati → Srisailam → Tirupati",
    routeFull: ["Tirupati", "Srisailam", "Tirupati"],
    image: "images/p3.jpg",
    highlights: ["Mallikarjuna Jyotirlinga", "Srisailam Dam", "Long Distance Comfort"],
    description: "Visit the magnificent Mallikarjuna Jyotirlinga at Srisailam — one of the 12 sacred Jyotirlingas of India. A long but profoundly rewarding journey.",
    note: "Long distance trip. Requires full-day commitment.",
    driverCost4s: 16000,
    commission4s: 1500,
    price7s: null,
    includes: ["Full day cab (return)", "Srisailam temple visit", "Driver allowance"],
    excludes: ["Entry tickets", "GST", "Meals"]
  },
  {
    id: "tirupati-mahabalipuram",
    name: "Tirupati → Mahabalipuram",
    category: "outstation",
    tag: "Coastal Trip",
    tagClass: "",
    popular: false,
    price: 8499,
    duration: "Full Day",
    routeShort: "Tirupati → Mahabalipuram → Tirupati",
    routeFull: ["Tirupati", "Mahabalipuram", "Tirupati"],
    image: "images/p1.jpg",
    highlights: ["Shore Temple", "Rock-Cut Caves", "Bay of Bengal", "UNESCO Heritage"],
    description: "A beautiful cultural and coastal excursion to Mahabalipuram's UNESCO World Heritage Site. Stunning rock-cut temples, the famous Shore Temple, and the serene Bay of Bengal.",
    note: "Outstation trip. Great for combining culture and coastal scenery.",
    driverCost4s: 7000,
    commission4s: 1499,
    price7s: null,
    includes: ["Full day cab (return)", "Mahabalipuram sightseeing", "Driver guide"],
    excludes: ["Entry tickets", "GST", "Meals"]
  }
];